"""Synthetic local-media fixtures for the Content Engine A1 to A6 rehearsal.

Every asset produced here is generated by this repository at test time:

- the WAV is a deterministic tone, never Kokoro output and never a human voice;
- the PNGs are flat synthetic frames, never photographs or model output;
- no download, network call, external API or third-party asset is involved.

The fixtures exist to exercise the real A3 import, A4 timing, A5 assembly and A6
originality contracts against each other. They do not validate narration
quality, editorial value, rights over real imagery or caption synchronism with a
real voice. Those still depend on Kokoro on the RTX 3090, a reviewed visual
package and human review, and remain explicitly pending.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
import wave
import zlib
from decimal import Decimal
from pathlib import Path
from types import SimpleNamespace

from src.pipeline.script_gen import ScriptResult
from src.pipeline.tts import TTSAdapterResult

REHEARSAL_LICENSE_ID = "PROJECT-SYNTHETIC-FIXTURE; scope=quality-test-only"
REHEARSAL_TTS_BACKEND = "synthetic_quality_test_fixture"
REHEARSAL_VOICE_ID = "synthetic_tone"
REHEARSAL_LANGUAGE_CODE = "p"
SYNTHETIC_SAMPLE_RATE_HZ = 24_000
SYNTHETIC_NARRATION_SECONDS = Decimal("12")
_SECONDS_PER_VISUAL = Decimal("6")
_TONE_BASE_HZ = 220.0
_TONE_AMPLITUDE = 9_000


def rehearsal_script() -> ScriptResult:
    """Return the fixed PT-BR editorial fixture used by the rehearsal."""
    return ScriptResult(
        angle="O sono consolida memórias recentes.",
        outline="1. Gancho\n2. Explicação\n3. Fecho",
        full_script=(
            "Durante o sono profundo o cérebro reorganiza conexões formadas no dia. "
            "Memórias úteis ganham força e detalhes irrelevantes perdem prioridade. "
            "Por isso dormir mal prejudica o aprendizado e a tomada de decisão."
        ),
        hook="Seu cérebro escolhe o que lembrar enquanto você dorme.",
        narration=(
            "Durante o sono profundo o cérebro reorganiza conexões formadas no dia. "
            "Memórias úteis ganham força e detalhes irrelevantes perdem prioridade."
        ),
    )


def expected_visual_count(duration_seconds: Decimal = SYNTHETIC_NARRATION_SECONDS) -> int:
    """Mirror the A3 rule of one visual per six seconds of verified audio."""
    return max(1, math.ceil(duration_seconds / _SECONDS_PER_VISUAL))


def write_synthetic_narration_wav(
    _text: str,
    destination: Path,
    voice_id: str,
    language_code: str,
) -> TTSAdapterResult:
    """Write a deterministic PCM S16LE mono tone in place of real narration."""
    frame_count = int(SYNTHETIC_NARRATION_SECONDS) * SYNTHETIC_SAMPLE_RATE_HZ
    samples = bytearray()
    for index in range(frame_count):
        seconds = index / SYNTHETIC_SAMPLE_RATE_HZ
        frequency = _TONE_BASE_HZ * (1.0 + 0.5 * math.floor(seconds / 3.0))
        value = int(_TONE_AMPLITUDE * math.sin(2.0 * math.pi * frequency * seconds))
        samples += struct.pack("<h", value)
    with wave.open(str(destination), "wb") as audio:
        audio.setnchannels(1)
        audio.setsampwidth(2)
        audio.setframerate(SYNTHETIC_SAMPLE_RATE_HZ)
        audio.writeframes(bytes(samples))
    return TTSAdapterResult(
        backend=REHEARSAL_TTS_BACKEND,
        model_id="deterministic-tone-v1",
        voice_id=voice_id,
        language_code=language_code,
        license_id=REHEARSAL_LICENSE_ID,
    )


def write_synthetic_visual_import(
    import_root: Path,
    *,
    count: int,
    width: int,
    height: int,
    manifest_name: str = "manifest.json",
) -> Path:
    """Publish synthetic PNGs plus a strict A3 manifest inside one contained root."""
    if count < 1:
        raise ValueError("rehearsal needs at least one visual")
    import_root.mkdir(parents=True, exist_ok=True)
    assets: list[dict[str, object]] = []
    for index in range(1, count + 1):
        file_name = f"rehearsal-{index:03d}.png"
        path = import_root / file_name
        path.write_bytes(_synthetic_png(width=width, height=height, index=index))
        assets.append(
            {
                "relative_path": file_name,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "source_type": "generated",
                "provider": "automation-foundry",
                "model_id": "synthetic-rehearsal-frame-v1",
                "source_id": f"rehearsal-frame-{index:03d}",
                "source_uri": (
                    "local-model://automation-foundry/synthetic-rehearsal-frame-v1/"
                    f"{index:03d}"
                ),
                "license_id": REHEARSAL_LICENSE_ID,
                "commercial_use": True,
                "attribution": (
                    "Quadro sintético gerado pelo próprio projeto para quality test; "
                    "não é imagem de terceiro nem substitui um pacote visual revisado."
                ),
            }
        )
    manifest_path = import_root / manifest_name
    manifest_path.write_text(
        json.dumps({"schema_version": 1, "assets": assets}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return manifest_path


def rehearsal_settings(
    storage_root: Path,
    *,
    import_root: Path,
    manifest_name: str = "manifest.json",
    assembly_backend: str = "fake_local_quality_test",
    ffmpeg_path: str = "ffmpeg",
    ffprobe_path: str = "ffprobe",
    ffmpeg_sha256: str | None = None,
    ffprobe_sha256: str | None = None,
    narration_review_enabled: bool = False,
    caption_alignment_gate_enabled: bool = False,
    final_review_enabled: bool = False,
    thumbnail_review_enabled: bool = False,
) -> SimpleNamespace:
    """Build the exact settings projection the A1 executor reads for one rehearsal."""
    return SimpleNamespace(
        storage_root=str(storage_root),
        ollama_model="rehearsal-fixture-model",
        celery_soft_time_limit_seconds=600,
        content_tts_backend=REHEARSAL_TTS_BACKEND,
        content_tts_voice_id=REHEARSAL_VOICE_ID,
        content_tts_language_code=REHEARSAL_LANGUAGE_CODE,
        content_narration_review_enabled=narration_review_enabled,
        content_visual_backend="local_assets_quality_test",
        content_visual_import_root=str(import_root),
        content_visual_manifest_path=manifest_name,
        content_caption_backend="approved_text_timing_quality_test",
        content_caption_alignment_gate_enabled=caption_alignment_gate_enabled,
        content_caption_alignment_min_speech_coverage=0.90,
        content_caption_alignment_max_outside_speech=0.25,
        content_caption_alignment_tolerance_seconds=0.50,
        content_assembly_backend=assembly_backend,
        content_ffmpeg_path=ffmpeg_path,
        content_ffprobe_path=ffprobe_path,
        content_ffmpeg_expected_sha256=ffmpeg_sha256,
        content_ffprobe_expected_sha256=ffprobe_sha256,
        content_similarity_threshold=0.85,
        content_similarity_window=20,
        content_final_review_enabled=final_review_enabled,
        content_thumbnail_review_enabled=thumbnail_review_enabled,
        gpu_power_watts=400,
        cpu_power_watts=150,
    )


def rehearsal_input_payload() -> dict[str, object]:
    """Return the manual A1 input used by every rehearsal execution."""
    return {
        "topic": "Sono profundo e consolidação de memória",
        "persona": "Ciência acessível em português brasileiro",
        "format": "short",
        "recent_openings": [],
    }


def _synthetic_png(*, width: int, height: int, index: int) -> bytes:
    red = (index * 53) % 256
    green = (index * 97) % 256
    blue = (index * 151) % 256
    row = b"\x00" + (bytes((red, green, blue)) * width)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(row * height, level=9))
        + _png_chunk(b"IEND", b"")
    )


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + kind
        + data
        + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    )
